## Traefik Global Configuration ##
global:
  checkNewVersion: false
  sendAnonymousUsage: false

## API and Dashboard Configuration ##
api:
  dashboard: false
  insecure: false

## EntryPoints Configuration ##
entryPoints:
  web:
    address: ":80"
    # Redirect to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

## TLS Configuration with Self-Signed Certificates ##
tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/local-cert.pem"
        keyFile: "/etc/traefik/certs/local-key.pem"
  options:
    default:
      minVersion: "VersionTLS12"
      sniStrict: true

## Providers Configuration ##
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "photoprism"
  file:
    directory: "/etc/traefik/conf.d"
    watch: true

## Log Configuration ##
log:
  level: "INFO" 