http:
  routers:
    photoprism:
      rule: "HostRegexp(`127.0.0.1`, `{subdomain:[a-z0-9-]+}.local`, `localhost`, `photoprism`, `photoprismpi`, `photoprism.local`, `{subdomain:[a-z0-9-]+}.photoprism.local`, `photoprismpi.local`, `{subdomain:[a-z0-9-]+}.photoprismpi.local`)"
      service: "photoprism"
      tls:
        domains:
          - main: "photoprism.local"
            sans:
              - "*.photoprism.local"
              - "photoprismpi.local"
              - "*.photoprismpi.local"
              - "localhost"
              - "*.local"
        certResolver: "default"
        options: "default"

  services:
    photoprism:
      loadBalancer:
        servers:
          - url: "http://photoprism:2342"

tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/local-cert.pem"
        keyFile: "/etc/traefik/certs/local-key.pem" 